ben_appointment:
    path:     /
    defaults: { _controller: "BenDoctorsBundle:Appointment:index" }

ben_appointment_show:
    path:     /{id}/show
    defaults: { _controller: "BenDoctorsBundle:Appointment:show" }

ben_appointment_new:
    path:     /new
    defaults: { _controller: "BenDoctorsBundle:Appointment:new" }

ben_appointment_create:
    path:     /create
    defaults: { _controller: "BenDoctorsBundle:Appointment:create" }
    methods:  POST

ben_appointment_edit:
    path:     /{id}/edit
    defaults: { _controller: "BenDoctorsBundle:Appointment:edit" }

ben_appointment_update:
    path:     /{id}/update
    defaults: { _controller: "BenDoctorsBundle:Appointment:update" }
    methods:  [POST, PUT]

ben_appointment_delete:
    path:     /{id}/delete
    defaults: { _controller: "BenDoctorsBundle:Appointment:delete" }
    methods:  [POST, DELETE]
